kind: Template
apiVersion: v1
metadata:
  name: openshift-demo
  annotations:
    openshift.io/display-name: "A demonstration for a general application building and deployment configuration"
    tags: "java,spring-boot"
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "${SOURCE_REPOSITORY_URL}"
labels:
  template: openshift-demo
  app: openshift-demo
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: openshift-demo
      annotations:
        description: "Keeps track of changes in the application image"
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: openshift-demo
      annotations:
        description: "Defines how to build the application"
    spec:
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
      strategy:
        type: Docker
        dockerStrategy: {}
      output:
        to:
          kind: ImageStreamTag
          name: openshift-demo:latest
      triggers: []
      nodeSelector: {}
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      annotations:
        description: "Exposes and load balances the application pods"
    spec:
      ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: "${APPLICATION_NAME}"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      annotations:
        description: "Defines how to deploy the application server"
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${APPLICATION_NAME}"
            from:
              kind: ImageStreamTag
              namespace: "${NAMESPACE}"
              name: "${APPLICATION_NAME}:latest"
        - type: ConfigChange
      replicas: 1
      selector:
        name: "${APPLICATION_NAME}"
      template:
        metadata:
          name: "${APPLICATION_NAME}"
          labels:
            name: "${APPLICATION_NAME}"
        spec:
          containers:
            - name: "${APPLICATION_NAME}"
              ports:
                - containerPort: 8080
                  protocol: TCP
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
parameters:
  - name: APPLICATION_NAME
    displayName: Name
    description: "The name assigned to all of the frontend objects defined in this template."
    required: true
    value: openshift-demo
  - name: NAMESPACE
    displayName: Namespace
    description: "The OpenShift Namespace where the ImageStream resides."
    required: true
    value: jobtech-openshift-demo
  - name: SOURCE_REPOSITORY_URL
    displayName: "Git Repository URL"
    description: "The URL of the repository with your application source code."
    required: true
    value: "https://github.com/taz-jt/openshift-demo.git"
  - name: SOURCE_REPOSITORY_REF
    displayName: "Git Reference"
    description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."
    required: true
    value: openshift-demo
